[package]
name = "roo"
version = "0.1.0"
authors = ["Zolt√°n Nagy <abesto@abesto.net>"]
edition = "2018"

[dependencies]
mlua = { version = "0.6.1", features = ["lua54", "vendored", "serde", "send", "async", "macros"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
tokio = { version = "1.5.0", features = ["full"] }
glob = "0.3.0"
async-channel = "1.6.1"
ron = "0.6.4"
serde = "1.0.126"
paste = "1.0.5"
clap = "3.0.0-beta.2"
include_dir = "0.6.1"
