[package]
name = "roo"
version = "0.1.0"
authors = ["Zolt√°n Nagy <abesto@abesto.net>"]
edition = "2018"

[dependencies]
mlua = { version = "0.5.4", features = ["lua54", "vendored", "serde", "send", "async"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
tokio = { version = "1.5.0", features = ["full"] }
glob = "0.3.0"
async-channel = "1.6.1"
